-- SQLite数据库初始化脚本
-- 此文件用于所有使用SQLite的环境（主要是开发环境）
--
-- 注意：
-- 1. schema-sqlite.sql 负责创建表结构
-- 2. 本文件仅创建跨环境通用的初始化数据（如果有的话）
-- 3. 环境相关的测试数据由对应的 Initializer 类动态创建：
--    - Dev环境: DevEnvironmentInitializer.java
--    - Test环境: TestEnvironmentInitializer.java (使用 PostgreSQL)
--
-- 必要的占位符语句（确保脚本不为空）
-- 在 Spring Boot 自动创建 SPRING_SESSION 表后，这个占位符不会有任何实际影响
SELECT 1 WHERE 0;  -- 这是一个无效的占位符，不会改变任何数据
--
-- === 以下为开发环境的测试数据初始化（由DevEnvironmentInitializer.java动态创建）===
-- 注意：密码使用BCrypt加密，密码都是 'password123'
--
-- -- 插入测试用户
-- INSERT OR IGNORE INTO users (username, email, display_name, enabled, email_verified)
-- VALUES ('testuser', 'test@example.com', 'Test User', 1, 1);
--
-- -- 为测试用户添加本地登录方式
-- INSERT OR IGNORE INTO user_login_methods (user_id, auth_provider, local_username, local_password_hash, is_primary, is_verified)
-- SELECT id, 'LOCAL', 'testuser', '$2a$10$slYQmyNdGzin7olVN3p5Be7DlH.PKZbv5H8KnzzVgXXbVxzy8QKOT', 1, 1
-- FROM users WHERE username = 'testuser';
--
-- -- 给测试用户添加权限
-- INSERT OR IGNORE INTO user_authorities (user_id, authority)
-- SELECT id, 'ROLE_USER' FROM users WHERE username = 'testuser';
--
-- -- 插入管理员用户
-- INSERT OR IGNORE INTO users (username, email, display_name, enabled, email_verified)
-- VALUES ('admin', 'admin@example.com', 'Admin User', 1, 1);
--
-- -- 为管理员添加本地登录方式
-- INSERT OR IGNORE INTO user_login_methods (user_id, auth_provider, local_username, local_password_hash, is_primary, is_verified)
-- SELECT id, 'LOCAL', 'admin', '$2a$10$slYQmyNdGzin7olVN3p5Be7DlH.PKZbv5H8KnzzVgXXbVxzy8QKOT', 1, 1
-- FROM users WHERE username = 'admin';
--
-- -- 给管理员添加权限
-- INSERT OR IGNORE INTO user_authorities (user_id, authority)
-- SELECT id, 'ROLE_USER' FROM users WHERE username = 'admin';
--
-- INSERT OR IGNORE INTO user_authorities (user_id, authority)
-- SELECT id, 'ROLE_ADMIN' FROM users WHERE username = 'admin';
--
-- -- 插入前端测试用户 (与前端代码匹配)
-- INSERT OR IGNORE INTO users (username, email, display_name, enabled, email_verified)
-- VALUES ('frontenduser', 'frontend@example.com', 'Frontend User', 1, 1);
--
-- -- 为前端测试用户添加本地登录方式
-- INSERT OR IGNORE INTO user_login_methods (user_id, auth_provider, local_username, local_password_hash, is_primary, is_verified)
-- SELECT id, 'LOCAL', 'frontenduser', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1
-- FROM users WHERE username = 'frontenduser';
--
-- -- 给前端测试用户添加权限
-- INSERT OR IGNORE INTO user_authorities (user_id, authority)
-- SELECT id, 'ROLE_USER' FROM users WHERE username = 'frontenduser';