# configuration:
#   sequenceNumber: 1000
#   boundedContextName: "A.AO.Demo"
#   metadata:
#     EventTypeDiscriminatorName: "EventType"
#     ServiceMethodMessagingCommandNameFormat: "{0}_{1}" # {ServiceName}_{MethodName}
#   ao:
#     objectVersionPropertyName: Version
