-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>

InventoryItemTable = InventoryItemTable and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(InventoryItemTable) or {}

ArticleTable = ArticleTable and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(ArticleTable) or {}

ArticleIdSequence = ArticleIdSequence and (
    function(old_data)
        -- Migrate from array format {0} to object format {current = "0"}
        if type(old_data) == "table" and type(old_data[1]) == "number" then
            return { current = tostring(old_data[1]) }
        end
        -- If already object format but value is number, convert to string
        if type(old_data) == "table" and type(old_data.current) == "number" then
            return { current = tostring(old_data.current) }
        end
        return old_data
    end
)(ArticleIdSequence) or { current = "0" }

CommentTable = CommentTable and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(CommentTable) or {}

EscrowPaymentTable = EscrowPaymentTable and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(EscrowPaymentTable) or {}

PaymentIdSequence = PaymentIdSequence and (
    function(old_data)
        -- Migrate from array format {0} to object format {current = "0"}
        if type(old_data) == "table" and type(old_data[1]) == "number" then
            return { current = tostring(old_data[1]) }
        end
        -- If already object format but value is number, convert to string
        if type(old_data) == "table" and type(old_data.current) == "number" then
            return { current = tostring(old_data.current) }
        end
        return old_data
    end
)(PaymentIdSequence) or { current = "0" }

NftEscrowTable = NftEscrowTable and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(NftEscrowTable) or {}

NftEscrowIdSequence = NftEscrowIdSequence and (
    function(old_data)
        -- Migrate from array format {0} to object format {current = "0"}
        if type(old_data) == "table" and type(old_data[1]) == "number" then
            return { current = tostring(old_data[1]) }
        end
        -- If already object format but value is number, convert to string
        if type(old_data) == "table" and type(old_data.current) == "number" then
            return { current = tostring(old_data.current) }
        end
        return old_data
    end
)(NftEscrowIdSequence) or { current = "0" }

SagaInstances = SagaInstances and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(SagaInstances) or {}

SagaIdSequence = SagaIdSequence and (
    function(old_data)
        -- Migrate from array format {0} to object format {current = "0"}
        if type(old_data) == "table" and type(old_data[1]) == "number" then
            return { current = tostring(old_data[1]) }
        end
        -- If already object format but value is number, convert to string
        if type(old_data) == "table" and type(old_data.current) == "number" then
            return { current = tostring(old_data.current) }
        end
        return old_data
    end
)(SagaIdSequence) or { current = "0" }


local json = require("json")
local entity_coll = require("entity_coll")
local messaging = require("messaging")
local saga = require("saga")
local inventory_item_id = require("inventory_item_id")
local article_comment_id = require("article_comment_id")
local inventory_item_aggregate = require("inventory_item_aggregate")
local article_aggregate = require("article_aggregate")
local escrow_payment_aggregate = require("escrow_payment_aggregate")
local nft_escrow_aggregate = require("nft_escrow_aggregate")
local inventory_service = require("inventory_service")
local nft_escrow_service = require("nft_escrow_service")

inventory_item_aggregate.init(InventoryItemTable)

article_aggregate.init(ArticleTable, ArticleIdSequence, CommentTable)

escrow_payment_aggregate.init(EscrowPaymentTable, PaymentIdSequence)

nft_escrow_aggregate.init(NftEscrowTable, NftEscrowIdSequence)

saga.init(SagaInstances, SagaIdSequence)


local function get_inventory_item(msg, env, response)
    local status, result = pcall((function()
        local cmd = json.decode(msg.Data)
        local _inventory_item_id = cmd.inventory_item_id
        local _key = json.encode(inventory_item_id.to_key_array(_inventory_item_id))
        local _state = entity_coll.get(InventoryItemTable, _key)
        return _state
    end))
    messaging.respond(status, result, msg)
end

local function add_inventory_item_entry(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return inventory_item_aggregate.add_inventory_item_entry(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

local function get_article(msg, env, response)
    local status, result = pcall((function()
        local cmd = json.decode(msg.Data)
        local article_id = cmd.article_id
        local _state = entity_coll.get(ArticleTable, article_id)
        return _state
    end))
    messaging.respond(status, result, msg)
end

local function get_comment(msg, env, response)
    local status, result = pcall((function()
        local cmd = json.decode(msg.Data)
        local _article_comment_id = cmd.article_comment_id
        local _key = json.encode(article_comment_id.to_key_array(_article_comment_id))
        local _state = entity_coll.get(CommentTable, _key)
        return _state
    end))
    messaging.respond(status, result, msg)
end

local function update_article_body(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return article_aggregate.update_body(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

local function create_article(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return article_aggregate.create(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

local function update_article(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return article_aggregate.update(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

local function add_comment(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return article_aggregate.add_comment(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

local function update_comment(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return article_aggregate.update_comment(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

local function remove_comment(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return article_aggregate.remove_comment(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

local function get_escrow_payment(msg, env, response)
    local status, result = pcall((function()
        local cmd = json.decode(msg.Data)
        local payment_id = cmd.payment_id
        local _state = entity_coll.get(EscrowPaymentTable, payment_id)
        return _state
    end))
    messaging.respond(status, result, msg)
end

-- local function create_escrow_payment(msg, env, response)
--     local status, result, commit = pcall((function()
--         local cmd = json.decode(msg.Data)
--         return escrow_payment_aggregate.create(cmd, msg, env)
--     end))
--     messaging.process_operation_result(status, result, commit, msg)
-- end

-- local function mark_as_used(msg, env, response)
--     local status, result, commit = pcall((function()
--         local cmd = json.decode(msg.Data)
--         return escrow_payment_aggregate.mark_as_used(cmd, msg, env)
--     end))
--     messaging.process_operation_result(status, result, commit, msg)
-- end

-- local function refund(msg, env, response)
--     local status, result, commit = pcall((function()
--         local cmd = json.decode(msg.Data)
--         return escrow_payment_aggregate.refund(cmd, msg, env)
--     end))
--     messaging.process_operation_result(status, result, commit, msg)
-- end

local function get_nft_escrow(msg, env, response)
    local status, result = pcall((function()
        local cmd = json.decode(msg.Data)
        local escrow_id = cmd.escrow_id
        local _state = entity_coll.get(NftEscrowTable, escrow_id)
        return _state
    end))
    messaging.respond(status, result, msg)
end

local function create_nft_escrow(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return nft_escrow_aggregate.create(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

Handlers.add(
    "get_inventory_item",
    Handlers.utils.hasMatchingTag("Action", "GetInventoryItem"),
    get_inventory_item
)

Handlers.add(
    "get_inventory_item_count",
    Handlers.utils.hasMatchingTag("Action", "GetInventoryItemCount"),
    function(msg, env, response)
        local count = 0
        for _ in pairs(InventoryItemTable) do
            count = count + 1
        end
        messaging.respond(true, count, msg)
    end
)

Handlers.add(
    "get_inventory_item_table_keys",
    Handlers.utils.hasMatchingTag("Action", "GetInventoryItemTableKeys"),
    function(msg, env, response)
        local keys = {}
        local n = 0
        for k, v in pairs(InventoryItemTable) do
            n = n + 1
            keys[n] = k
        end
        messaging.respond(true, keys, msg)
    end
)

Handlers.add(
    "add_inventory_item_entry",
    Handlers.utils.hasMatchingTag("Action", "AddInventoryItemEntry"),
    add_inventory_item_entry
)

Handlers.add(
    "get_article",
    Handlers.utils.hasMatchingTag("Action", "GetArticle"),
    get_article
)

Handlers.add(
    "get_comment",
    Handlers.utils.hasMatchingTag("Action", "GetComment"),
    get_comment
)

Handlers.add(
    "get_article_count",
    Handlers.utils.hasMatchingTag("Action", "GetArticleCount"),
    function(msg, env, response)
        local count = 0
        for _ in pairs(ArticleTable) do
            count = count + 1
        end
        messaging.respond(true, count, msg)
    end
)

Handlers.add(
    "get_article_id_sequence",
    Handlers.utils.hasMatchingTag("Action", "GetArticleIdSequence"),
    function(msg, env, response)
        messaging.respond(true, ArticleIdSequence, msg)
    end
)

Handlers.add(
    "update_article_body",
    Handlers.utils.hasMatchingTag("Action", "UpdateArticleBody"),
    update_article_body
)

Handlers.add(
    "create_article",
    Handlers.utils.hasMatchingTag("Action", "CreateArticle"),
    create_article
)

Handlers.add(
    "update_article",
    Handlers.utils.hasMatchingTag("Action", "UpdateArticle"),
    update_article
)

Handlers.add(
    "add_comment",
    Handlers.utils.hasMatchingTag("Action", "AddComment"),
    add_comment
)

Handlers.add(
    "update_comment",
    Handlers.utils.hasMatchingTag("Action", "UpdateComment"),
    update_comment
)

Handlers.add(
    "remove_comment",
    Handlers.utils.hasMatchingTag("Action", "RemoveComment"),
    remove_comment
)

Handlers.add(
    "get_escrow_payment",
    Handlers.utils.hasMatchingTag("Action", "GetEscrowPayment"),
    get_escrow_payment
)

Handlers.add(
    "get_escrow_payment_count",
    Handlers.utils.hasMatchingTag("Action", "GetEscrowPaymentCount"),
    function(msg, env, response)
        local count = 0
        for _ in pairs(EscrowPaymentTable) do
            count = count + 1
        end
        messaging.respond(true, count, msg)
    end
)

Handlers.add(
    "get_payment_id_sequence",
    Handlers.utils.hasMatchingTag("Action", "GetPaymentIdSequence"),
    function(msg, env, response)
        messaging.respond(true, PaymentIdSequence, msg)
    end
)

-- 内部方法，不应该生成 message handlers

-- Handlers.add(
--     "create_escrow_payment",
--     Handlers.utils.hasMatchingTag("Action", "CreateEscrowPayment"),
--     create_escrow_payment
-- )

-- Handlers.add(
--     "mark_as_used",
--     Handlers.utils.hasMatchingTag("Action", "MarkAsUsed"),
--     mark_as_used
-- )

-- Handlers.add(
--     "refund",
--     Handlers.utils.hasMatchingTag("Action", "Refund"),
--     refund
-- )

Handlers.add(
    "get_nft_escrow",
    Handlers.utils.hasMatchingTag("Action", "GetNftEscrow"),
    get_nft_escrow
)

Handlers.add(
    "get_nft_escrow_count",
    Handlers.utils.hasMatchingTag("Action", "GetNftEscrowCount"),
    function(msg, env, response)
        local count = 0
        for _ in pairs(NftEscrowTable) do
            count = count + 1
        end
        messaging.respond(true, count, msg)
    end
)

Handlers.add(
    "create_nft_escrow",
    Handlers.utils.hasMatchingTag("Action", "CreateNftEscrow"),
    create_nft_escrow
)


Handlers.add(
    "get_sage_instance",
    Handlers.utils.hasMatchingTag("Action", "GetSagaInstance"),
    function(msg, env, response)
        local cmd = json.decode(msg.Data)
        local saga_id = cmd.saga_id
        local s = entity_coll.get(SagaInstances, saga_id)
        messaging.respond(true, s, msg)
    end
)

Handlers.add(
    "saga_timeout_check",
    Handlers.utils.hasMatchingTag("Action", "Saga_TimeoutCheck"),
    function(msg)
        local saga_id = tonumber(msg.Tags["X-SagaId"])
        local check_time = tonumber(msg.Tags["X-CheckTime"])

        if not saga_id or not check_time then
            print("Invalid timeout check request: missing saga_id or check_time")
            return
        end

        -- Get Saga instance
        local saga_instance = saga.get_saga_instance_copy(saga_id)
        if not saga_instance then
            print("Saga instance not found: " .. saga_id)
            return
        end

        -- Check if Saga is in waiting state
        if not saga_instance.waiting_state or not saga_instance.waiting_state.is_waiting then
            print("Saga not waiting: " .. saga_id)
            return
        end

        -- Validate waiting state
        local waiting_start_time = saga_instance.waiting_state.started_at
        local max_wait_seconds = saga_instance.waiting_state.max_wait_time_seconds

        if not waiting_start_time or not max_wait_seconds then
            print("Invalid waiting state for saga: " .. saga_id)
            return
        end

        -- Check if timeout has occurred
        local elapsed_time = check_time - waiting_start_time
        if elapsed_time >= max_wait_seconds then
            -- Timeout confirmed, get failure event type
            local failure_event_type = saga_instance.waiting_state.failure_event_type
            if failure_event_type then
                -- Trigger failure event via trigger_local_event
                print("Saga timeout confirmed: " .. saga_id .. ", elapsed: " .. elapsed_time .. "s. Triggering failure event: " .. failure_event_type)
                saga.trigger_local_event(saga_id, failure_event_type, {reason = "TIMEOUT"})
            else
                -- No failureEvent defined, ignore timeout check
                print("INFO: Timeout check for Saga " .. saga_id .. ", but no failureEvent defined. Ignoring timeout.")
            end
        else
            -- Not timeout yet
            print("Saga not timeout yet: " .. saga_id .. ", elapsed: " .. elapsed_time .. "s")
        end
    end
)

Handlers.add(
    "get_sage_id_sequence",
    Handlers.utils.hasMatchingTag("Action", "GetSagaIdSequence"),
    function(msg, env, response)
        messaging.respond(true, SagaIdSequence, msg)
    end
)


Handlers.add(
    "inventory_service_process_inventory_surplus_or_shortage",
    Handlers.utils.hasMatchingTag("Action", inventory_service.ACTIONS.PROCESS_INVENTORY_SURPLUS_OR_SHORTAGE),
    inventory_service.process_inventory_surplus_or_shortage
)

Handlers.add(
    "inventory_service_process_inventory_surplus_or_shortage_get_inventory_item_callback",
    Handlers.utils.hasMatchingTag("Action",
        inventory_service.ACTIONS.PROCESS_INVENTORY_SURPLUS_OR_SHORTAGE_GET_INVENTORY_ITEM_CALLBACK),
    inventory_service.process_inventory_surplus_or_shortage_get_inventory_item_callback
)

Handlers.add(
    "inventory_service_process_inventory_surplus_or_shortage_create_single_line_in_out_callback",
    Handlers.utils.hasMatchingTag("Action",
        inventory_service.ACTIONS.PROCESS_INVENTORY_SURPLUS_OR_SHORTAGE_CREATE_SINGLE_LINE_IN_OUT_CALLBACK),
    inventory_service.process_inventory_surplus_or_shortage_create_single_line_in_out_callback
)

Handlers.add(
    "inventory_service_process_inventory_surplus_or_shortage_create_single_line_in_out_compensation_callback",
    Handlers.utils.hasMatchingTag("Action",
        inventory_service.ACTIONS.PROCESS_INVENTORY_SURPLUS_OR_SHORTAGE_CREATE_SINGLE_LINE_IN_OUT_COMPENSATION_CALLBACK),
    inventory_service.process_inventory_surplus_or_shortage_create_single_line_in_out_compensation_callback
)

Handlers.add(
    "inventory_service_process_inventory_surplus_or_shortage_add_inventory_item_entry_callback",
    Handlers.utils.hasMatchingTag("Action",
        inventory_service.ACTIONS.PROCESS_INVENTORY_SURPLUS_OR_SHORTAGE_ADD_INVENTORY_ITEM_ENTRY_CALLBACK),
    inventory_service.process_inventory_surplus_or_shortage_add_inventory_item_entry_callback
)

Handlers.add(
    "inventory_service_process_inventory_surplus_or_shortage_complete_in_out_callback",
    Handlers.utils.hasMatchingTag("Action",
        inventory_service.ACTIONS.PROCESS_INVENTORY_SURPLUS_OR_SHORTAGE_COMPLETE_IN_OUT_CALLBACK),
    inventory_service.process_inventory_surplus_or_shortage_complete_in_out_callback
)

-- NFT Escrow Service handlers (added for reference)
Handlers.add(
    "nft_escrow_service_use_escrow_payment",
    Handlers.utils.hasMatchingTag("Action",
        nft_escrow_service.ACTIONS.USE_ESCROW_PAYMENT),
    nft_escrow_service.use_escrow_payment
)

Handlers.add(
    "nft_escrow_service_execute_nft_escrow_transaction",
    Handlers.utils.hasMatchingTag("Action", 
        nft_escrow_service.ACTIONS.EXECUTE_NFT_ESCROW_TRANSACTION),
    nft_escrow_service.execute_nft_escrow_transaction
)

