-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>

local escrow_payment = {}

local ERRORS = {
}

escrow_payment.ERRORS = ERRORS


--- Creates a new EscrowPayment state.
--
-- @param payer_address string 
-- @param token_contract string 
-- @param amount bint 
-- @param status string 
-- @param used_by_escrow_id bint 
-- @return table A new state table representing the EscrowPayment.
function escrow_payment.new(payer_address, token_contract, amount, status, used_by_escrow_id)
    local state = {
        version = "0",
        payer_address = payer_address,
        token_contract = token_contract,
        amount = amount,
        status = status,
        used_by_escrow_id = used_by_escrow_id,
    }
    return state
end

--- Creates a new EscrowPaymentCreated event.
-- @param payment_id bint The PaymentId of the EscrowPayment
-- @param payer_address string 
-- @param token_contract string 
-- @param amount bint 
-- @param status string 
-- @param used_by_escrow_id bint 
-- @param created_at number 
-- @return table
function escrow_payment.new_escrow_payment_created(payment_id, payer_address, token_contract, amount, status, used_by_escrow_id, created_at)
    local event = {}
    event.event_type = "EscrowPaymentCreated"
    event.payment_id = payment_id
    event.payer_address = payer_address
    event.token_contract = token_contract
    event.amount = amount
    event.status = status
    event.used_by_escrow_id = used_by_escrow_id
    event.created_at = created_at
    return event
end

--- Creates a new MarkAsUsedEvent event.
-- @param _state table The current state of the EscrowPayment
-- @param escrow_id bint 
-- @return table
function escrow_payment.new_mark_as_used_event(_state, escrow_id)
    local event = {}
    event.event_type = "MarkAsUsedEvent"
    event.payment_id = _state.payment_id
    event.version = _state.version
    event.escrow_id = escrow_id
    return event
end

--- Creates a new RefundEvent event.
-- @param _state table The current state of the EscrowPayment
-- @return table
function escrow_payment.new_refund_event(_state)
    local event = {}
    event.event_type = "RefundEvent"
    event.payment_id = _state.payment_id
    event.version = _state.version
    return event
end

return escrow_payment
