-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>

local entity_coll = require("entity_coll")
local bint = require('.bint')(256)
local json = require("json")

local escrow_payment_aggregate = {}

local ERRORS = {
    NIL_ENTITY_ID_SEQUENCE = "NIL_ENTITY_ID_SEQUENCE",
    ENTITY_ID_MISMATCH = "ENTITY_ID_MISMATCH",
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT",
    VERSION_MISMATCH = "VERSION_MISMATCH",
}

escrow_payment_aggregate.ERRORS = ERRORS

local escrow_payment_table
local payment_id_sequence

function escrow_payment_aggregate.init(table, sequence)
    escrow_payment_table = table
    payment_id_sequence = sequence
end

-- Internal methods only - no external message handlers
-- Methods are called internally by services

return escrow_payment_aggregate
