-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>

InventoryItemTable = InventoryItemTable and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(InventoryItemTable) or {}


SagaInstances = SagaInstances and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(SagaInstances) or {}

SagaIdSequence = SagaIdSequence and (
    function(old_data)
        -- May need to migrate old data
        return old_data
    end
)(SagaIdSequence) or { 0 }


local json = require("json")
local entity_coll = require("entity_coll")
local messaging = require("messaging")
local saga = require("saga")
local inventory_item_id = require("inventory_item_id")
local inventory_item_aggregate = require("inventory_item_aggregate")

inventory_item_aggregate.init(InventoryItemTable)

saga.init(SagaInstances, SagaIdSequence)


local function get_inventory_item(msg, env, response)
    local status, result = pcall((function()
        local cmd = json.decode(msg.Data)
        local _inventory_item_id = cmd.inventory_item_id
        local _key = json.encode(inventory_item_id.to_key_array(_inventory_item_id))
        local _state = entity_coll.get(InventoryItemTable, _key)
        return _state
    end))
    if msg.reply then
        msg.reply(result)
    else
        Send({Target = msg.From, Data = json.encode(result)})
    end
end

local function add_inventory_item_entry(msg, env, response)
    local status, result, commit = pcall((function()
        local cmd = json.decode(msg.Data)
        return inventory_item_aggregate.add_inventory_item_entry(cmd, msg, env)
    end))
    messaging.process_operation_result(status, result, commit, msg)
end

Handlers.add(
    "get_inventory_item",
    Handlers.utils.hasMatchingTag("Action", "GetInventoryItem"),
    get_inventory_item
)

Handlers.add(
    "get_inventory_item_count",
    Handlers.utils.hasMatchingTag("Action", "GetInventoryItemCount"),
    function(msg, env, response)
        local count = 0
        for _ in pairs(InventoryItemTable) do
            count = count + 1
        end
        if msg.reply then
            msg.reply({count = count})
        else
            Send({Target = msg.From, Data = json.encode({count = count})})
        end
    end
)

Handlers.add(
    "get_inventory_item_table_keys",
    Handlers.utils.hasMatchingTag("Action", "GetInventoryItemTableKeys"),
    function(msg, env, response)
        local keys = {}
        local n = 0
        for k, v in pairs(InventoryItemTable) do
            n = n + 1
            keys[n] = k
        end
        if msg.reply then
            msg.reply({keys = keys})
        else
            Send({Target = msg.From, Data = json.encode({keys = keys})})
        end
    end
)

Handlers.add(
    "add_inventory_item_entry",
    Handlers.utils.hasMatchingTag("Action", "AddInventoryItemEntry"),
    add_inventory_item_entry
)


Handlers.add(
    "get_sage_instance",
    Handlers.utils.hasMatchingTag("Action", "GetSagaInstance"),
    function(msg, env, response)
        local cmd = json.decode(msg.Data)
        local saga_id = cmd.saga_id
        local s = entity_coll.get(SagaInstances, saga_id)
        if msg.reply then
            msg.reply(s)
        else
            Send({Target = msg.From, Data = json.encode(s)})
        end
    end
)


Handlers.add(
    "get_sage_id_sequence",
    Handlers.utils.hasMatchingTag("Action", "GetSagaIdSequence"),
    function(msg, env, response)
        if msg.reply then
            msg.reply(SagaIdSequence)
        else
            Send({Target = msg.From, Data = json.encode(SagaIdSequence)})
        end
    end
)


