-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>

local entity_coll = require("entity_coll")
local bint = require('.bint')(256)
local json = require("json")

local nft_escrow_aggregate = {}

local ERRORS = {
    NIL_ENTITY_ID_SEQUENCE = "NIL_ENTITY_ID_SEQUENCE",
    ENTITY_ID_MISMATCH = "ENTITY_ID_MISMATCH",
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT",
    VERSION_MISMATCH = "VERSION_MISMATCH",
}

nft_escrow_aggregate.ERRORS = ERRORS

local nft_escrow_table

function nft_escrow_aggregate.init(table)
    nft_escrow_table = table
end

-- Internal methods only - no external message handlers
-- Methods are called internally by services

return nft_escrow_aggregate
