-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>

local nft_escrow = {}

local ERRORS = {
}

nft_escrow.ERRORS = ERRORS


--- Creates a new NftEscrow state.
--
-- @param escrow_id bint 
-- @param seller_address string 
-- @param buyer_address string 
-- @param nft_contract string 
-- @param token_id bint 
-- @param token_contract string 
-- @param price bint 
-- @param payment_id bint 
-- @param escrow_terms string 
-- @return table A new state table representing the NftEscrow.
function nft_escrow.new(escrow_id, seller_address, buyer_address, nft_contract, token_id, token_contract, price, payment_id, escrow_terms)
    local state = {
        escrow_id = escrow_id,
        version = "0",
        seller_address = seller_address,
        buyer_address = buyer_address,
        nft_contract = nft_contract,
        token_id = token_id,
        token_contract = token_contract,
        price = price,
        payment_id = payment_id,
        escrow_terms = escrow_terms,
    }
    return state
end

--- Creates a new NftEscrowCreated event.
-- @param escrow_id bint The EscrowId of the NftEscrow
-- @param seller_address string 
-- @param buyer_address string 
-- @param nft_contract string 
-- @param token_id bint 
-- @param token_contract string 
-- @param price bint 
-- @param payment_id bint 
-- @param escrow_terms string 
-- @param created_at number 
-- @return table
function nft_escrow.new_nft_escrow_created(escrow_id, seller_address, buyer_address, nft_contract, token_id, token_contract, price, payment_id, escrow_terms, created_at)
    local event = {}
    event.event_type = "NftEscrowCreated"
    event.escrow_id = escrow_id
    event.seller_address = seller_address
    event.buyer_address = buyer_address
    event.nft_contract = nft_contract
    event.token_id = token_id
    event.token_contract = token_contract
    event.price = price
    event.payment_id = payment_id
    event.escrow_terms = escrow_terms
    event.created_at = created_at
    return event
end

return nft_escrow
